env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - binary: nomad-vector-logger.bin
    id: nomad-vector-logger
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.buildString={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
    dir: .

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
      - config.sample.toml

dockers:
  - # ID of the image, needed if you want to filter by it later on (e.g. on custom publishers).
    id: nomad-vector-logger

    # GOOS of the built binaries/packages that should be used.
    goos: linux

    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64

    # IDs to filter the binaries/packages.
    ids:
      - nomad-vector-logger

    # Templates of the Docker image names.
    image_templates:
      - "ghcr.io/mr-karan/nomad-vector-logger:{{ .Tag }}"
      - "ghcr.io/mr-karan/nomad-vector-logger:latest"
    
    skip_push: false
    dockerfile: Dockerfile
    use: docker
    # Template of the docker build flags.
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

    extra_files:
      - config.sample.toml
