[sources.source_nomad_alloc_7687b251-2861-0f4d-02d0-2496fa7d9e9a_proxy]
type = "file"
include = [ "/opt/nomad/data/alloc/7687b251-2861-0f4d-02d0-2496fa7d9e9a/alloc/logs/proxy*" ]
line_delimiter = "\n"
read_from = "beginning"
[transforms.transform_nomad_alloc_7687b251-2861-0f4d-02d0-2496fa7d9e9a_proxy]
type = "remap"
inputs = ["source_nomad_alloc_7687b251-2861-0f4d-02d0-2496fa7d9e9a_proxy"]
source = '''
# Store Nomad metadata.
.nomad.namespace = "default"
.nomad.node_name = "pop-os"
.nomad.job_name = "nginx"
.nomad.group_name = "nginx"
.nomad.task_name = "proxy"
.nomad.alloc_id = "7687b251-2861-0f4d-02d0-2496fa7d9e9a"
'''
